<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-OJU0P6V" failures="1" tests="41" name="com.qa.tests.DataExchangeAdmin" time="228.304" errors="2" timestamp="2024-05-20T20:37:35 IST" skipped="0">
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="Credentilas" time="4.004"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="Admin_APIConnectivity" time="0.939"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="AdminDashboard" time="1.529"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="Admin_SearchUsersByName" time="1.270"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="Admin_IsUserPresent" time="1.421"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="CustomAttributes" time="2.415"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="UpdateSystemUser" time="0.914"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="EnableDisableSystemUser" time="1.345"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="AgencyDistribution" time="2.364"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="AgencyAll" time="2.315"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="historicalbatches" time="0.993"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="batchdetail" time="0.973"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="downloadbatchdetail" time="1.303"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="mapping" time="1.320"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="client" time="0.937"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="alertmessage" time="1.022"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reference_agency" time="1.002"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reference_role" time="0.949"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reference_userdisablereason" time="1.064"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reeference_template" time="29.113"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_landing" time="0.957"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_failedlogins" time="35.344"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_activelogins" time="24.361">
    <error message="JSONArray[0] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONArray[0] not found.
at org.json.JSONArray.get(JSONArray.java:264)
at com.qa.util.TestUtil.getValueByjpath(TestUtil.java:16)
at com.qa.tests.DataExchangeAdmin.reports_activelogins(DataExchangeAdmin.java:1134)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- reports_activelogins -->
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_loginhistory" time="54.379"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_newaccounts" time="4.642"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_queryhistory" time="1.962"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_seaechesperformedbyuser" time="2.281"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_multiauthorization" time="3.494"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_entitydetails" time="1.376"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_employeeworkinghours" time="29.926"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="searchreason" time="0.981">
    <error message="JSONObject[&quot;clientname&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["clientname"] not found.
at org.json.JSONObject.get(JSONObject.java:572)
at com.qa.util.TestUtil.getValueByjpath(TestUtil.java:14)
at com.qa.tests.DataExchangeAdmin.searchreason(DataExchangeAdmin.java:1361)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- searchreason -->
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="searchreasondetail" time="0.930"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="searchreasonsusers" time="1.521"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="individualsearch" time="1.012"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="entitysearch" time="0.916"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="monthlyentity" time="1.024"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="monthlyindividual" time="1.387"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="downloadreport" time="1.221"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="total_workflow" time="1.215"/>
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="workflow_by_id" time="1.117">
    <failure message="status code is not 200 expected [200] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: status code is not 200 expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at com.qa.tests.DataExchangeAdmin.workflow_by_id(DataExchangeAdmin.java:1547)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- workflow_by_id -->
  <system-out/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="workflow_client" time="1.066"/>
  <system-out/>
</testsuite> <!-- com.qa.tests.DataExchangeAdmin -->
