<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OJU0P6V" failures="9" tests="47" name="DataExchangeAdmin" time="314.628" errors="0" timestamp="2024-04-07T13:34:43 IST">
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="Credentilas" time="9.246"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="Admin_APIConnectivity" time="3.11"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="AdminDashboard" time="3.837"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="Admin_SearchUsersByName" time="5.81"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="Admin_IsUserPresent" time="1.908"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="CustomAttributes" time="106.408"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="CreateSysyemUser" time="2.007"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="UpdateSystemUser" time="0.923"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="EnableDisableSystemUser" time="1.489"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="AgencyDistribution" time="1.882"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="AgencyAll" time="0.867"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="batch_fileupload" time="0.853">
    <failure type="java.lang.AssertionError" message="status code is not 200 expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: status code is not 200 expected [200] but found [400]
at com.qa.tests.DataExchangeAdmin.batch_fileupload(DataExchangeAdmin.java:641)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- batch_fileupload -->
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="batch_statusupdate" time="0.851"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="historicalbatches" time="0.825"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="batch_downloadfile" time="0.835">
    <failure type="java.lang.AssertionError" message="status code is not 200 expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: status code is not 200 expected [200] but found [405]
at com.qa.tests.DataExchangeAdmin.batch_downloadfile(DataExchangeAdmin.java:764)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- batch_downloadfile -->
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="batchdetail" time="0.902"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="downloadbatchdetail" time="4.075"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="savebatchdetail" time="0.861">
    <failure type="java.lang.AssertionError" message="status code is not 200 expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: status code is not 200 expected [200] but found [405]
at com.qa.tests.DataExchangeAdmin.savebatchdetail(DataExchangeAdmin.java:830)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- savebatchdetail -->
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="alertmessage" time="3.303"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reference_agency" time="0.855"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reference_role" time="0.828"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reference_userdisablereason" time="0.808"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reeference_template" time="0.796"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_landing" time="0.838"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_failedlogins" time="19.609"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_activelogins" time="17.354">
    <failure type="org.json.JSONException" message="JSONArray[0] not found.">
      <![CDATA[org.json.JSONException: JSONArray[0] not found.
at org.json.JSONArray.get(JSONArray.java:264)
at com.qa.util.TestUtil.getValueByjpath(TestUtil.java:16)
at com.qa.tests.DataExchangeAdmin.reports_activelogins(DataExchangeAdmin.java:1057)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- reports_activelogins -->
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_loginhistory" time="19.072"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_newaccounts" time="2.519"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_queryhistory" time="4.282"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_queryhistoryfiltered" time="4.204"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_seaechesperformedbyuser" time="3.187"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_multiauthorization" time="4.715"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_entitydetails" time="3.062"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="reports_employeeworkinghours" time="26.077"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="searchreason" time="3.278">
    <failure type="org.json.JSONException" message="JSONArray[0] not found.">
      <![CDATA[org.json.JSONException: JSONArray[0] not found.
at org.json.JSONArray.get(JSONArray.java:264)
at com.qa.util.TestUtil.getValueByjpath(TestUtil.java:16)
at com.qa.tests.DataExchangeAdmin.searchreason(DataExchangeAdmin.java:1278)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- searchreason -->
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="searchreasondetail" time="3.032">
    <failure type="org.json.JSONException" message="JSONArray[0] not found.">
      <![CDATA[org.json.JSONException: JSONArray[0] not found.
at org.json.JSONArray.get(JSONArray.java:264)
at com.qa.util.TestUtil.getValueByjpath(TestUtil.java:16)
at com.qa.tests.DataExchangeAdmin.searchreasondetail(DataExchangeAdmin.java:1306)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- searchreasondetail -->
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="linkuser" time="0.79">
    <failure type="java.lang.AssertionError" message="status code is not 200 expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: status code is not 200 expected [200] but found [400]
at com.qa.tests.DataExchangeAdmin.linkuser(DataExchangeAdmin.java:1326)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- linkuser -->
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="searchreasonsusers" time="3.014">
    <failure type="org.json.JSONException" message="JSONArray[0] not found.">
      <![CDATA[org.json.JSONException: JSONArray[0] not found.
at org.json.JSONArray.get(JSONArray.java:264)
at com.qa.util.TestUtil.getValueByjpath(TestUtil.java:16)
at com.qa.tests.DataExchangeAdmin.searchreasonsusers(DataExchangeAdmin.java:1363)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- searchreasonsusers -->
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="individualsearch" time="3.298"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="entitysearch" time="3.048"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="monthlyentity" time="3.11"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="monthlyindividual" time="3.3"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="downloadreport" time="25.218"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="workflows" time="3.325"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="workflow_method" time="3.024"/>
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="save_workflowmthod" time="0.836">
    <failure type="java.lang.AssertionError" message="status code is not 200 expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: status code is not 200 expected [200] but found [405]
at com.qa.tests.DataExchangeAdmin.save_workflowmthod(DataExchangeAdmin.java:1540)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- save_workflowmthod -->
  <testcase classname="com.qa.tests.DataExchangeAdmin" name="workflow_client" time="0.811"/>
</testsuite> <!-- DataExchangeAdmin -->
